### ISSUE TITLE
require vs import

### ISSUE THREAD

**Issue by corroded** [ajhyndman/fire-emblem-working-title#101]
Hi, playing around with the heroes stats and when I try to do this:

```
var stats = require('fire-emblem-heroes-stats')
console.log(stats)
```

it works like you said: it returns an object plus all the methods of `stats`

but when i do this (used `yarn add fire-emblem-heroes-stats`)

```
import stats from 'fire-emblem-heroes-stats'
console.log(stats)
```

only returns the Object array with heroes and skills. Is this intended behaviour?

**Comment by corroded** [comment]
my bad! it should be

```
import * as stats from 'fire-emblem-heroes-stats'
```

Sorry for the confusion!

**Comment by ajhyndman** [comment]
Glad you worked it out, @corroded!  If you have any other questions, feel free to ask.  👍
