### ISSUE TITLE
Source for portraits

### ISSUE THREAD

**Issue by corroded** [ajhyndman/fire-emblem-working-title#102]
Hi, do you just scrape the portraits from fehwiki as well? Can I suggest that links to them be added to the hero stats? :)

**Comment by ajhyndman** [comment]
Yeah, that's not a bad idea.

We are scraping images from the wiki as well, but hosting them via our own server connected to Cloudflare's CDN.

**Comment by corroded** [comment]
Nice! I'd create a PR but i couldn't get `lerna` running from my machine haha

**Comment by ajhyndman** [comment]
I'd like to make the project a bit easier to use.  What kind of issues did you run into?  I have been wanting to expand the README a bit.

**Comment by corroded** [comment]
I will double check again when I get home. It was a couple of weeks back. 

Also, might be in another issue, but would also suggest to add which heroes and what rarity a skill has. I think it's a common use case especially for SI planning tools :)

**Comment by ajhyndman** [comment]
You mean as a property on the skill stats object itself?  I'd definitely like to see some better SI planning tools.

I think that might actually be better suited as a helper function in `fire-emblem-heroes-calculator`.  Maybe in [heroHelpers](https://github.com/ajhyndman/fire-emblem-working-title/blob/master/packages/fire-emblem-heroes-calculator/src/heroHelpers.js)?  I've been trying to keep the stats.json file itself pretty *normalised*.  If the same information is persisted in more than one place, there's a greater chance that it will at some point get out of sync.

**Comment by ajhyndman** [comment]
I've pushed a change in `v0.9.0`.  Let me know how you feel about that.

https://github.com/ajhyndman/fire-emblem-working-title/commit/e02b65c0ab4f60d7d150b7c5c41b7488912b2903

**Comment by corroded** [comment]
<3 it! All good! Can't wait to work on my calc again :)

Also I haven't seen heroHelpers! Maybe that's just what I need. I can give you the helper function I have for selecting those skills:

```
  static heroesForSkill(skillName) {
    const heroesWithSkill = Heroes.filter((hero) => {
      return hero.skills.filter((skill) => {
        return skill.name === skillName
      }).length > 0
    })

    return heroesWithSkill.map((hero) => {
      return {
        name: hero.name,
        rarity: hero.skills.find((skill) => {
          return (skill.name === skillName)
        }).rarity
      }
    })
  }

```

**Comment by corroded** [comment]
Closing this issue now though since you already fixed it with your commit 👍
