### ISSUE TITLE
Error stats.json

### ISSUE THREAD

**Issue by altemuller** [ajhyndman/fire-emblem-working-title#104]
Fix please +res Nino. Not 30. 29.

**Comment by ajhyndman** [comment]
I'll have a look tonight!

**Comment by ajhyndman** [comment]
Are you sure @dmiltso?  It looks like the feheroes wiki has +res Nino at 30.

https://feheroes.gamepedia.com/Nino

MassDuelSimulator also puts Nino's resistance at 30.

http://andyiverson.me/apps/fehmasssimulator/

Do you happen to have any screenshots to demonstrate?

**Comment by dmiltso** [comment]
lol, really? Nino have +4 iv?

**Comment by ajhyndman** [comment]
If you spot any other bugs, please let me know!
