### ISSUE TITLE
Prevent OS date formatting from leaking into `stats.json`

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#121]
It looks like the date format currently in `stats.json` is influenced by OS settings.  Look for a way to prevent that from happening.

In the worst case, maybe use timestamps instead of datestrings here?

**Comment by carsomyr** [comment]
<img width="668" alt="screen shot 2018-02-13 at 2 24 33 pm" src="https://user-images.githubusercontent.com/555005/36169239-b5d56de8-10c9-11e8-9826-c5706966204e.png">

These are default settings for English (US). We could just revert [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601), which is the wiki's format.

**Comment by ajhyndman** [comment]
Yeah, that seems reasonable.

**Comment by ajhyndman** [comment]
Resolved in #127.  Thanks @carsomyr!
