### ISSUE TITLE
Rhajat portraits are actually Winter Tharja's

### ISSUE THREAD

**Issue by GanonZack** [ajhyndman/fire-emblem-working-title#125]
What the title says.

**Comment by ajhyndman** [comment]
Huh, that's a good one, thanks for that.  I wonder how that happened.

**Comment by GanonZack** [comment]
You're welcome. I navigated through the assets, you only have to replace Rhajat's portraits (Winter Tharja's ones, they're named after Rhajat) with the originals.

**Comment by ajhyndman** [comment]
Yep, I've got the right ones ready, too.  I just have to remember to push the changes when I'm free!
