### ISSUE TITLE
New heroes?

### ISSUE THREAD

**Issue by MattTheNub** [ajhyndman/fire-emblem-working-title#145]
It's been almost 2 months since the last update to `fire-emblem-heroes-stats`. Are new heroes going to be added any time soon?

**Comment by ajhyndman** [comment]
Whoah, someone is using these stats?  :)

Sure, I'll try to run an update shortly.  I'm not sure how regularly I'll be updating in the future, so I'd be happy to help show anyone that's interested how to fetch updates locally, or contribute updates to this repository.

**Comment by ajhyndman** [comment]
I've published [v0.15.2](https://github.com/ajhyndman/fire-emblem-working-title/releases/tag/v0.15.2) with the latest results of a scrape!  Let me know if you have any issues.
