### ISSUE TITLE
One-click to choose a hero if there is an empty box

### ISSUE THREAD

**Issue by AlmostMatt** [ajhyndman/fire-emblem-working-title#23]
If either of the two hero boxes at the top are empty, clicking on a hero in the list should select it.

**Comment by ajhyndman** [comment]
@AlmostMatt I thought about this, but I want to add up to eight boxes in the end.  It's not clear which slot we should assume you want out of those eight when you click on your first hero.

I also think it would be a break from the game's UI.  Matching the game UI, which anyone who might use this app should be familiar with, probably gives us some ease-of-use for free.

**Comment by AlmostMatt** [comment]
This would actually match the ingame UI. When editing a team, if there are any empty spaces on the team and I click on one of my heroes it is instantly added to the first available slot on the team.

As for the order of the slots, it would be attacker, defender, attacking-allies 1-3, defending-allies 1-3

**Comment by ajhyndman** [comment]
Hmm.  Yeah alright, sounds worth trying out!

**Comment by AlmostMatt** [comment]
https://github.com/ajhyndman/fire-emblem-working-title/commit/6e18b19c78ddb99abdc998ce8930fe7830ce70f3
