### ISSUE TITLE
Calculate the damage dealt via special skills

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#32]

**Comment by AlmostMatt** [comment]
It would probably be nice to have something in the GUI to indicate/change the current cooldown.

I'm a little bit uncertain about how skills like death blow, hone atk, and spur atk interact with specials (also things like armored blow and bonfire)

**Comment by ajhyndman** [comment]
I agree on the GUI.  This probably needs a little design thought.

I'm not expecting to handle it now, but I'd also like to start thinking about how we might enable multi-turn combat results (#50).  I do like being able to get all the information that you can on AnduCrandu's mass duel simulator.
