### ISSUE TITLE
If a hero doesn't have a weapon equipped, they should do 0 damage

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#40]
https://www.reddit.com/r/FireEmblemHeroes/comments/61izix/i_made_a_mass_duel_simulator/dff1o61/?utm_content=permalink&utm_medium=front&utm_source=reddit&utm_name=FireEmblemHeroes

**Comment by AlmostMatt** [comment]
It's kind of a silly feature to support.

Technically though an unarmed hero is unable to attack and does not retaliate when attacked. (so numAttacks = 0)

**Comment by ajhyndman** [comment]
It just seemed like a mistake that had been made, so worth learning from.

**Comment by ajhyndman** [comment]
I'll double check what happens.  I think I'll also enable "unsetting" skills and deselecting heroes with this card.

**Comment by AlmostMatt** [comment]
I added a way to unselect skills and then added a check for no weapon => cant attack

**Comment by ajhyndman** [comment]
Nice!
