### ISSUE TITLE
Add a 'last-updated-on' date to the site

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#51]
I think this is a good way to build confidence in the stats.  If we can't have current information, users will get frustrated.

**Comment by AlmostMatt** [comment]
At least for stats this can be automated. The JSON object can have an additional field for last-updated.

**Comment by ajhyndman** [comment]
Mm, yeah.  I like that idea.

**Comment by ajhyndman** [comment]
I still like the idea of stamping the stats, but for now I've added a script to the deployment process that stamps a date into the build.

**Comment by ajhyndman** [comment]
I think we'll call this done for now.

3321f73ef7bd7d61e4b2b28295e577a149789da6
