### ISSUE TITLE
Fetch Info for unreleased heroes

### ISSUE THREAD

**Issue by AlmostMatt** [ajhyndman/fire-emblem-working-title#54]
Use https://feheroes.wiki/Hero_List instead of https://feheroes.wiki/Stats_Table and inspect the release date to determine whether or not a hero is released.

This is somewhat optional, but they have hero pages, art, and some known skills so we might as well fetch it.

**Comment by ajhyndman** [comment]
I think you're right.  I thought about suggesting that too.
