### ISSUE TITLE
Add some indication of special damage / postcombat damage / lifesteal

### ISSUE THREAD

**Issue by AlmostMatt** [ajhyndman/fire-emblem-working-title#62]
A possible mockup
https://www.figma.com/file/Pf9yyM9iXjXhLseegpGgPSvn/Specials-Postcombat-Dmg-and-Lifesteal

**Comment by AlmostMatt** [comment]
I added a simple purple text indication for the total special damage done in a combat, so this is sort of resolved.

**Comment by ajhyndman** [comment]
Yeah... I don't know.  It seems pretty intuitive so far.  Maybe we wait until a brilliant idea strikes us, or people start complaining about it to do anything further.

If we do a toggle-able combat log someday, that would also help address this.

I'll close for now.  I set up a follow-up issue to tickle us once in a while in case we come up with something great. #85
