### ISSUE TITLE
Compute all missing variations

### ISSUE THREAD

**Issue by AlmostMatt** [ajhyndman/fire-emblem-working-title#65]
Verify the claims made at the following page and use them to predict all 5 star variations (and 3/4 star variations as well if possible)
https://www.reddit.com/r/FireEmblemHeroes/comments/61wfqz/regarding_base_stat_totals_growth_rates_and_max/

Either apply missing numbers to the wiki or update the app/scraper to fill in the blanks.

**Comment by ajhyndman** [comment]
What's the minimal amount of data we need from the wiki now in order to compute all stats?  Am I right in understanding that there's no point in scraping variance now?

**Comment by AlmostMatt** [comment]
I think that we only need **5\* level 1 and level 40 normal variants**, and it should be possible to infer all variants. 
It also sounds like the 3* and 4* growths can be inferred from growth points which can be inferred from 5* stats, but I'm not quite sure whether or not we can infer level 1 stats for 3* and 4* heroes.

We would also want to indicate whether or not a hero can have variance (GrandHeroBattle heroes and Sharena/Alfonse/Anna do not)

From a comment on the linked page:

Growth Value	5* Gain	4* Gain	3* Gain
0	8	8	?
1	10	10	9
2	13	12	11
3	15	14	13
4	17	16	15
5	19	18	17
6	22	20	19
7	24	22	21
8	26	24	23
9	28	26	25
10	30	28	27
11	33	30	?

So we compute statGain = lvl40 - lvl1, and then use this table to find growthPoints.
For a level 1 bane/boon it's +-1 stat
For a level 40 bane/boon it's +-1 stat and also +-1 growthPoints (which works out to 2 or 3 stats)

**Comment by ajhyndman** [comment]
Cool!  I'm thinking that our stats file actually probably only stores the growth points and level 1 stats then?  I'd like that layer of calculation to be explicit and reviewable.

We can potentially generate a second stats output from the first with actual computed stat values, if that's useful.

**Comment by AlmostMatt** [comment]
It seems that the wiki people used that logic to compute variations, so we should have all variations now.

It would still be sort of nice to have a version of stats that is just base stats and growth points, but it's a pretty low priority for now.

**Comment by ajhyndman** [comment]
Cool, seems right. 👍

**Comment by ajhyndman** [comment]
I guess, as-defined, this card is done.
