### ISSUE TITLE
Support merged heroes.

### ISSUE THREAD

**Issue by AlmostMatt** [ajhyndman/fire-emblem-working-title#66]
The stats gained from merging heroes is deterministic, according to:
https://feheroes.wiki/Merge_Allies

So we could add UI for levels like 40+1 and 40+10.

**Comment by ajhyndman** [comment]
Whoah!  Awesome!

**Comment by AlmostMatt** [comment]
I added code support for merged hero stats in https://github.com/ajhyndman/fire-emblem-working-title/commit/e3d63a53f891a458f8506e60af13b8a09f2dd19f, but I leave the UI to you.

Presumably you can have a drop-down or a text field or up/down arrows or something to edit it.

**Comment by ajhyndman** [comment]
UI support added here: 2b113780edf837315b22d2668a8797a19735a5ce
