### ISSUE TITLE
Find a better icon for Sacred Seals (S Passives)

### ISSUE THREAD

**Issue by AlmostMatt** [ajhyndman/fire-emblem-working-title#76]
I drew an S in paint, and hopefully it is replaced eventually.

**Comment by ajhyndman** [comment]
I messaged the guy who's been maintaining this thread:

https://www.reddit.com/r/FireEmblemHeroes/comments/5rxtc7/fire_emblem_heroes_assets_collection_all_art/

He was able to dig out the official version.  👍 

http://i.imgur.com/uENR5al.png

**Comment by ajhyndman** [comment]
Fixed in 8b2c8dbcb92daa05922bfcb014aff19008b5a89a
