### ISSUE TITLE
Make any keydown event autofocus the filter input

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#79]
It's annoying having to use the mouse to click on it.

Things to be wary of: make sure it doesn't capture key events meant for:
- the address bar
- copy/paste?

**Comment by AlmostMatt** [comment]
Alternatively, can we have any mouse-down event give the filter focus? (Excluding the configure page)

If keydown events give it focus the user won't know that it has focus so they won't start typing.
If mousedown events give it focus the user will notice that it has focus and start typing.

**Comment by ajhyndman** [comment]
I pushed a change that implements this, care to give it a try?
