### ISSUE TITLE
Provide a means to save customized heroes locally

### ISSUE THREAD

**Issue by AlmostMatt** [ajhyndman/fire-emblem-working-title#80]
For example, I have a team of heroes that I use often. I want to be able to save them so that I can come back at a later time and see how my unit does against some specific enemy.

This would be relevant for checking damage for a specific enemy in an actual game, or for saving customized opponents like Fury Lucina, Vantage Takumi, Swordbreaker Nowi, etc.

I was thinking that if we could add tabs above the hero list at some point for this sort of thing (all heroes, my heroes, etc)

**Comment by ajhyndman** [comment]
Yeah, I've been wanting something like this too.  Technically you could just create a bunch of links and save them somewhere.  But who wants to do that.

**Comment by ajhyndman** [comment]
I think #55 will make this doable.
