### ISSUE TITLE
Consider exporting shareable text-based stats from a hero

### ISSUE THREAD

**Issue by ajhyndman** [ajhyndman/fire-emblem-working-title#83]
Inspired by conversation here:

https://ss.reddit.com/r/FireEmblemHeroes/comments/660lyv/what_if_we_had_a_streamlined_universal_statbuild/

One solution might be to add a share button on the "configure page" as well?

**Comment by ajhyndman** [comment]
Suggestions from reddit (/u/puncharino):

> This page would be my go-to page on my phone without a doubt if it were an app. The other simulators, while great, don't have a mobile friendly interface and yours is by far the most elegant solution I've seen for mobile. Have you thought about making, say, a native Android app? I feel like you'd profit from some ad revenue and it being the only native app on the Play Store that has it might make it notable. I'm not one to talk much though, I have no experience with programming or monetization. Just a thought, seeing as it's your API and it would not necessarily need to be constantly maintained unless bug reports or new data arise.
> As for the exportable format, maybe you could ask one of the devs of PKMN Showdown or Smogon. What they do is that they put the selected traits of a character in an editable text field (basically identical to the ones Reddit uses) so that users can copy-paste or further modify the exportable list. If you need a format, they say that imitation is the best form of flattery, so maybe something like:

```md
Anna (Neutral w/ Attack +1)
Weapon: Nóatún
Assist: Swap
Special: Iceberg
- Fury 3
- Desperation 3
- Threaten Spd 3
```

> Anyways, you keep doing what you're doing, I like the app a ton. Have a great day!

**Comment by AlmostMatt** [comment]
A slight variation:

       Anna: 5★ +10 +Atk -HP
     Weapon: Nóatún
     Assist: Swap
    Special: Iceberg
          A: Fury 3
          B: Desperation 3
          C: Threaten Spd 3
       Seal: Embla's Ward

or

    Anna (5★ +10 +Atk -HP)
    Nóatún
    Swap
    Iceberg
    Fury 3
    Desperation 3
    Threaten Spd 3

Though I think I like the left aligned text with labels.  
We could also technically create textual output for combat too, but you would need to list the inherited skills as well for it to make sense.

    Cherche  vs  Takumi:
    46 > 46      40 > 0
    24 x 2       37 x 2

**Comment by AlmostMatt** [comment]
(The close issue button is way too easy to push by mistake)

**Comment by ajhyndman** [comment]
Haha

**Comment by ajhyndman** [comment]
I think we can't rely on people only using these shareable stats in monospace font, so I'm opposed to this version:

```
   Anna: 5★ +10 +Atk -HP
 Weapon: Nóatún
 Assist: Swap
Special: Iceberg
      A: Fury 3
      B: Desperation 3
      C: Threaten Spd 3
   Seal: Embla's Ward
```

I think we might still need skill types in case of more name collisions in the future.  Maybe:

```
Anna (5★ +10 +Atk -HP)
Weapon: Nóatún
Assist: Swap
Special: Iceberg
Passive A: Fury 3
Passive B: Desperation 3
Passive C: Threaten Spd 3
Seal: Atk +1
```

I suppose if the order is fixed, then maybe it isn't confusing.

I sent a message to @Andu2, just in case he's interested in collaborating.  If this becomes a thing, it'd be better if multiple tools agree on a format.

**Comment by ajhyndman** [comment]
![image](https://cloud.githubusercontent.com/assets/11449340/25700090/63407e7e-3109-11e7-9e98-82ba01252b2e.png)

**Comment by Andu2** [comment]
I have internet again! Yay! I should be implementing my copy to clipboard feature next weekend or so. I think I'm just going to go with the basic "Attribute: value" every line thing unless someone stops me:

```
Anna (5★ +10 +atk -hp)  
Weapon: [Noatun/Nóatún]
Assist: Swap  
Special: Iceberg  
[Passive A/A]: Fury 3  
[Passive B/B]: Desperation 3  
[Passive C/C]: Threaten Spd 3  
[Passive S/S/Seal]: Atk [1/+1]
:::Status
Buff: atk 2, spd 6
Damage taken: 9
```

In square brackets are where I will support multiple names for things. I will be making everything lowercase to parse, and I will be replacing letters with diacritics with their base letters, because that's how it's stored in my database. My database also currently stores skills like "Atk +2" as "Atk 2", but perhaps I will add the pluses in.

**Comment by ajhyndman** [comment]
@Andu2 Awesome!  And thanks for the response.

We've been trying to adhere to the exact spelling used in the game, since it seemed like the most likely to be agreed upon across tools.  I don't think it matters too much which format we use, but it's a win if we both use the same one.  👍 

I like `attribute: value` better than something order-dependent too, because it's more resilient to parsing failures, typos and missing lines.  So I say do it!
